## Numpy

In [2]:
import numpy as np

1. Create an `ndarray` of shape (3,5). All values of the array are 100.

In [14]:
x = np.full((3, 5), 100)
x

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

2. Create a border of zeros that surround the result in Question 1, so that the output is of shape (5,7), the outside values are 0 and the inside values are 100. 

In [15]:
np.pad(x, 1, 'constant', constant_values=0)

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0, 100, 100, 100, 100, 100,   0],
       [  0, 100, 100, 100, 100, 100,   0],
       [  0, 100, 100, 100, 100, 100,   0],
       [  0,   0,   0,   0,   0,   0,   0]])

3. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal.


In [11]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

4. Create a checkerboard 8x8 matrix using the tile function

In [9]:
x = np.array([[1, 0], [0, 1]])
np.tile(x, (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

5. Sort a 2d-array by the nth column

In [29]:
x = np.random.randn(3,4) 
print(x)

[[-0.4876548  -2.06478948  0.05583286 -0.88847236]
 [ 0.07140234 -0.74709627  1.55159228  0.38886768]
 [-0.2049267  -0.21682552  0.04224953 -0.02947343]]


In [30]:
n = 3
x[x[:, n].argsort()]

array([[-0.4876548 , -2.06478948,  0.05583286, -0.88847236],
       [-0.2049267 , -0.21682552,  0.04224953, -0.02947343],
       [ 0.07140234, -0.74709627,  1.55159228,  0.38886768]])

6. Compute a matrix rank

In [31]:
np.linalg.matrix_rank(x)

3

7. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?

In [33]:
x1 = np.arange(75).reshape((5,5,3))
x2 = np.arange(25).reshape((5,5))

x1 * x2[:, :, np.newaxis] #

array([[[   0,    0,    0],
        [   3,    4,    5],
        [  12,   14,   16],
        [  27,   30,   33],
        [  48,   52,   56]],

       [[  75,   80,   85],
        [ 108,  114,  120],
        [ 147,  154,  161],
        [ 192,  200,  208],
        [ 243,  252,  261]],

       [[ 300,  310,  320],
        [ 363,  374,  385],
        [ 432,  444,  456],
        [ 507,  520,  533],
        [ 588,  602,  616]],

       [[ 675,  690,  705],
        [ 768,  784,  800],
        [ 867,  884,  901],
        [ 972,  990, 1008],
        [1083, 1102, 1121]],

       [[1200, 1220, 1240],
        [1323, 1344, 1365],
        [1452, 1474, 1496],
        [1587, 1610, 1633],
        [1728, 1752, 1776]]])

8. Consider a 16x16 array, how to get the block-sum (block size is 4x4)?

In [36]:
x = np.arange(256).reshape((16,16))
x.reshape((4,4,4,4)).sum(axis=(1,3)) #

array([[ 408,  472,  536,  600],
       [1432, 1496, 1560, 1624],
       [2456, 2520, 2584, 2648],
       [3480, 3544, 3608, 3672]])

9. Get the n largest values of an array

In [38]:
x = np.random.randn(6)
print(x)

n = 2
x[x.argsort()[-n:]]

[ 0.310176    2.02598317  1.73482772  0.91096793 -0.1068205   0.46896433]


array([1.73482772, 2.02598317])

10. Implement the Game of Life using numpy arrays

In [42]:
#

Check https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb for more Numpy exercises.

## Pandas

In [39]:
import pandas as pd
import seaborn as sb

1. Using NumPy, create a Pandas DataFrame with five rows and three columns

In [40]:
pd.DataFrame(np.arange(15).reshape(5,3))

0   1   2
0   0   1   2
1   3   4   5
2   6   7   8
3   9  10  11
4  12  13  14

The following six questions depend on the penguins dataset.

In [41]:
df_penguins = sb.load_dataset('penguins')

2. What function can we use to drop the rows that have missing data?

In [45]:
df_penguins.dropna()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0    Adelie  Torgersen            39.1           18.7              181.0   
1    Adelie  Torgersen            39.5           17.4              186.0   
2    Adelie  Torgersen            40.3           18.0              195.0   
4    Adelie  Torgersen            36.7           19.3              193.0   
5    Adelie  Torgersen            39.3           20.6              190.0   
..      ...        ...             ...            ...                ...   
338  Gentoo     Biscoe            47.2           13.7              214.0   
340  Gentoo     Biscoe            46.8           14.3              215.0   
341  Gentoo     Biscoe            50.4           15.7              222.0   
342  Gentoo     Biscoe            45.2           14.8              212.0   
343  Gentoo     Biscoe            49.9           16.1              213.0   

     body_mass_g     sex  
0         3750.0    Male  
1         3800.0  Female  
2         3250.0  Female  
4         3450.0  Female  
5         3650.0    Male  
..           ...     ...  
338       4925.0  Female  
340       4850.0  Female  
341       5750.0    Male  
342       5200.0  Female  
343       5400.0    Male  

[333 rows x 7 columns]

3. By default, will the function in Question 2 modify df_penguins or will it return a copy?

A: It will return a copy.

4. Let df_full be the dataframe obtained from dropping rows with missing data. What is the average bill length of a penguin, in millimeters, in this (df_full) data set?

In [47]:
df_penguins.dropna().bill_length_mm.mean()

43.99279279279279

5. Which species has the longest flippers?

In [52]:
idx = df_penguins['flipper_length_mm'].idxmax()
df_penguins.loc[idx, 'species']

'Gentoo'

6. Which two species have the most similar mean weight?

In [57]:
df_penguins.groupby('species').body_mass_g.mean() # Adelie and Chinstrap have the most similar mean weight.

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

7. How could you sort by species first, then by body mass?

In [58]:
df_penguins.sort_values(by=['species', 'body_mass_g'])

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
58   Adelie     Biscoe            36.5           16.6              181.0   
64   Adelie     Biscoe            36.4           17.1              184.0   
54   Adelie     Biscoe            34.5           18.1              187.0   
98   Adelie      Dream            33.1           16.1              178.0   
116  Adelie  Torgersen            38.6           17.0              188.0   
..      ...        ...             ...            ...                ...   
297  Gentoo     Biscoe            51.1           16.3              220.0   
337  Gentoo     Biscoe            48.8           16.2              222.0   
253  Gentoo     Biscoe            59.6           17.0              230.0   
237  Gentoo     Biscoe            49.2           15.2              221.0   
339  Gentoo     Biscoe             NaN            NaN                NaN   

     body_mass_g     sex  
58        2850.0  Female  
64        2850.0  Female  
54        2900.0  Female  
98        2900.0  Female  
116       2900.0  Female  
..           ...     ...  
297       6000.0    Male  
337       6000.0    Male  
253       6050.0    Male  
237       6300.0    Male  
339          NaN     NaN  

[344 rows x 7 columns]

The following three questions depend on the taxis dataset.

In [59]:
df_taxis = sb.load_dataset('taxis')

8. The 'pickup' column contains the date and time the customer picked up, but it's a string.  Add a column to the DataFrame, 'pickup_time', containing the value in 'pickup' as a DateTime.

In [61]:
df_taxis['pickup_time'] = pd.to_datetime(df_taxis['pickup'])
df_taxis

pickup              dropoff  passengers  distance  fare  \
0     2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0   
1     2019-03-04 16:11:55  2019-03-04 16:19:00           1      0.79   5.0   
2     2019-03-27 17:53:01  2019-03-27 18:00:25           1      1.37   7.5   
3     2019-03-10 01:23:59  2019-03-10 01:49:51           1      7.70  27.0   
4     2019-03-30 13:27:42  2019-03-30 13:37:14           3      2.16   9.0   
...                   ...                  ...         ...       ...   ...   
6428  2019-03-31 09:51:53  2019-03-31 09:55:27           1      0.75   4.5   
6429  2019-03-31 17:38:00  2019-03-31 18:34:23           1     18.74  58.0   
6430  2019-03-23 22:55:18  2019-03-23 23:14:25           1      4.14  16.0   
6431  2019-03-04 10:09:25  2019-03-04 10:14:29           1      1.12   6.0   
6432  2019-03-13 19:31:22  2019-03-13 19:48:02           1      3.85  15.0   

       tip  tolls  total   color      payment            pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card        Lenox Hill West   
1     0.00    0.0   9.30  yellow         cash  Upper West Side South   
2     2.36    0.0  14.16  yellow  credit card          Alphabet City   
3     6.15    0.0  36.95  yellow  credit card              Hudson Sq   
4     1.10    0.0  13.40  yellow  credit card           Midtown East   
...    ...    ...    ...     ...          ...                    ...   
6428  1.06    0.0   6.36   green  credit card      East Harlem North   
6429  0.00    0.0  58.80   green  credit card                Jamaica   
6430  0.00    0.0  17.30   green         cash    Crown Heights North   
6431  0.00    0.0   6.80   green  credit card          East New York   
6432  3.36    0.0  20.16   green  credit card            Boerum Hill   

                          dropoff_zone pickup_borough dropoff_borough  \
0                  UN/Turtle Bay South      Manhattan       Manhattan   
1                Upper West Side South      Manhattan       Manhattan   
2                         West Village      Manhattan       Manhattan   
3                       Yorkville West      Manhattan       Manhattan   
4                       Yorkville West      Manhattan       Manhattan   
...                                ...            ...             ...   
6428              Central Harlem North      Manhattan       Manhattan   
6429  East Concourse/Concourse Village         Queens           Bronx   
6430                    Bushwick North       Brooklyn        Brooklyn   
6431      East Flatbush/Remsen Village       Brooklyn        Brooklyn   
6432                   Windsor Terrace       Brooklyn        Brooklyn   

             pickup_time  
0    2019-03-23 20:21:09  
1    2019-03-04 16:11:55  
2    2019-03-27 17:53:01  
3    2019-03-10 01:23:59  
4    2019-03-30 13:27:42  
...                  ...  
6428 2019-03-31 09:51:53  
6429 2019-03-31 17:38:00  
6430 2019-03-23 22:55:18  
6431 2019-03-04 10:09:25  
6432 2019-03-13 19:31:22  

[6433 rows x 15 columns]

In [62]:
df_taxis.dtypes

pickup                     object
dropoff                    object
passengers                  int64
distance                  float64
fare                      float64
tip                       float64
tolls                     float64
total                     float64
color                      object
payment                    object
pickup_zone                object
dropoff_zone               object
pickup_borough             object
dropoff_borough            object
pickup_time        datetime64[ns]
dtype: object

9. Create a subset of the dataframe to create a new DataFrame, taxis_one_day. This new DataFrame should have pickup_time values between '2019-03-23 00:06:00' (inclusive) and '2019-03-24 00:00:00' (exlusive).

In [63]:
df_taxis.query("pickup_time >= '2019-03-23 00:06:00' and pickup_time <= '2019-03-24 00:00:00'")

pickup              dropoff  passengers  distance  fare  \
0     2019-03-23 20:21:09  2019-03-23 20:27:24           1      1.60   7.0   
8     2019-03-23 11:48:50  2019-03-23 12:06:14           1      3.63  15.0   
17    2019-03-23 20:50:49  2019-03-23 21:02:07           1      2.60  10.5   
117   2019-03-23 09:39:25  2019-03-23 09:56:45           0      3.60  15.5   
144   2019-03-23 18:35:01  2019-03-23 18:47:39           1      3.20  12.5   
...                   ...                  ...         ...       ...   ...   
6325  2019-03-23 20:52:40  2019-03-23 21:10:12           1      3.62  14.5   
6331  2019-03-23 11:27:00  2019-03-23 12:20:11           1      7.67  28.0   
6338  2019-03-23 18:05:38  2019-03-23 18:25:36           1      2.82  14.0   
6427  2019-03-23 18:26:09  2019-03-23 18:49:12           1      7.07  20.0   
6430  2019-03-23 22:55:18  2019-03-23 23:14:25           1      4.14  16.0   

       tip  tolls  total   color      payment                     pickup_zone  \
0     2.15    0.0  12.95  yellow  credit card                 Lenox Hill West   
8     1.00    0.0  19.30  yellow  credit card               East Harlem South   
17    2.00    0.0  16.30  yellow  credit card                  Midtown Center   
117   3.75    0.0  22.55  yellow  credit card                  Yorkville East   
144   2.00    0.0  17.80  yellow  credit card             UN/Turtle Bay South   
...    ...    ...    ...     ...          ...                             ...   
6325  0.00    0.0  15.80   green         cash  Long Island City/Hunters Point   
6331  0.00    0.0  28.00   green         cash                 Jackson Heights   
6338  0.00    0.0  14.80   green  credit card              Claremont/Bathgate   
6427  0.00    0.0  20.00   green         cash                     Parkchester   
6430  0.00    0.0  17.30   green         cash             Crown Heights North   

                      dropoff_zone pickup_borough dropoff_borough  \
0              UN/Turtle Bay South      Manhattan       Manhattan   
8                   Midtown Center      Manhattan       Manhattan   
17               East Harlem South      Manhattan       Manhattan   
117   Penn Station/Madison Sq West      Manhattan       Manhattan   
144                   East Village      Manhattan       Manhattan   
...                            ...            ...             ...   
6325                      Steinway         Queens          Queens   
6331                       Maspeth         Queens          Queens   
6338    Spuyten Duyvil/Kingsbridge          Bronx           Bronx   
6427             East Harlem South          Bronx       Manhattan   
6430                Bushwick North       Brooklyn        Brooklyn   

             pickup_time  
0    2019-03-23 20:21:09  
8    2019-03-23 11:48:50  
17   2019-03-23 20:50:49  
117  2019-03-23 09:39:25  
144  2019-03-23 18:35:01  
...                  ...  
6325 2019-03-23 20:52:40  
6331 2019-03-23 11:27:00  
6338 2019-03-23 18:05:38  
6427 2019-03-23 18:26:09  
6430 2019-03-23 22:55:18  

[209 rows x 15 columns]

10. From the dataframe in Question 9, take the mean of the numeric columns, grouped at one hour intervals.  Save the result as df_means, and display it.

In [64]:
df_taxis_one_day = df_taxis.query("pickup_time >= '2019-03-23 00:06:00' and pickup_time <= '2019-03-24 00:00:00'")
df_taxis_one_day.groupby([df_taxis_one_day['pickup_time'].dt.hour]).mean()

passengers  distance       fare       tip     tolls      total
pickup_time                                                                
0              1.000000  1.911667   8.583333  1.415000  0.000000  12.965000
1              1.250000  1.325000   7.875000  1.525000  0.000000  12.575000
2              1.727273  1.739091   8.181818  1.641818  0.000000  13.169091
3              1.500000  3.377500  11.750000  2.410000  0.000000  17.335000
4              2.000000  0.950000   5.500000  0.915000  0.000000  10.215000
5              2.000000  1.270000   6.000000  0.980000  0.000000  10.530000
6              1.000000  0.400000  21.500000  0.000000  0.000000  23.133333
7              2.333333  0.980000   5.250000  1.165000  0.000000   9.298333
8              1.000000  0.020000   2.500000  0.000000  0.000000   3.300000
9              1.500000  1.352000   7.400000  1.674000  0.000000  12.124000
10             1.000000  1.760000   8.750000  0.727500  0.000000  12.152500
11             1.909091  2.070000  11.090909  0.803636  0.000000  14.667273
12             2.000000  2.267143  10.260000  0.645714  0.000000  13.420000
13             2.500000  1.167000   7.550000  2.074000  0.000000  12.344000
14             2.470588  4.752941  18.330000  1.945294  1.003529  24.267059
15             1.000000  6.557143  22.214286  3.210000  1.645714  30.370000
16             2.000000  2.194545  10.454545  1.109091  0.000000  14.431818
17             1.090909  1.913636  14.818182  2.688182  0.523636  20.739091
18             1.571429  3.206429  12.821429  0.844286  0.411429  16.427143
19             1.526316  2.097895  10.263158  1.176316  0.000000  14.226316
20             1.400000  2.448000  11.100000  1.544000  0.000000  15.944000
21             1.000000  2.017143  10.571429  1.420000  0.000000  15.791429
22             1.307692  1.881538   8.923077  1.094615  0.000000  13.433077
23             1.615385  3.725385  15.115385  1.696154  0.000000  20.034615

Check https://colab.research.google.com/github/CodeSolid/CodeSolid.github.io/blob/main/booksource/exercises/PandasExercises.ipynb for more Pandas exercises.